#pragma once

enum ColorFormat
{
	COLOR_FORMAT_UNKNOWN,
	COLOR_FORMAT_R8,
	COLOR_FORMAT_RG8,
	COLOR_FORMAT_RGBA8,
	COLOR_FORMAT_RGBA16,
	COLOR_FORMAT_RGBA32,
	COLOR_FORMAT_RGBA16F,
	COLOR_FORMAT_RGBA32F
};
